name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Google Test
      run: sudo apt-get install -y libgtest-dev

    - uses: actions/checkout@v3
    - name: configure
      run: mkdir build; 
           cd build; 
           cmake ../
    - name: make
      run: make
    - name: execute the code
      run: ./cpp_test_ci
